language: node_js

node_js:
  - "10.11"

os:
  - linux
  #- osx
#
#compiler:
#  - gcc
#  - clang

before_install:
  - travis_retry npm i -g npm@6.4.0

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      brew update;
#      brew upgrade node;
#
#    else
#      sudo apt-get update;
#      sudo apt-get install npm;
#    fi

  #- bash travis_scripts/get_os.sh

  #- echo "$OS_NAME"

install:
  - travis_retry npm install
  - travis_retry npm update
  - travis_retry ./node_modules/.bin/electron-builder

script:
  #- npm run build
  #- npm run "$OS_NAME"
  - npm run ng-high-memory && npm run linux
