language: node_js

node_js:
  - "10.11"

os:
  - linux
  - osx
#
#compiler:
#  - gcc
#  - clang

before_install:
  - travis_retry npm i -g npm@6.4.0

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      brew update;
#      brew upgrade node;
#
#    else
#      sudo apt-get update;
#      sudo apt-get install npm;
#    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      export OS_NAME="linux"
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]
    then
      export OS_NAME="windows"
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      export OS_NAME="mac"
    fi

  - echo "$OS_NAME"

install: travis_retry npm install

script:
  - npm run build
  - npm run "$OS_NAME"
