language: node_js

node_js:
  - "10.13"

os:
  - linux
  - osx

#compiler:
#  - gcc
##  - clang

before_install:
  - travis_retry npm i -g npm@6.4.0

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      brew update;
#      brew upgrade node;
#
#    else
#      sudo apt-get update;
#      sudo apt-get install npm;
#    fi

install: travis_retry npm install

script:
  - npm run build
