language: generic
#node_js:
  #- '10.11'
os:
  - linux
  #- osx
script:
  - touch blank.txt
  - ls
#before_deploy:
  # Set up git user name and tag this commit
  #- git config --local user.name "causeyc"
  #- git config --local user.email "causeyc@findlay.edu"
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  #- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: iRdxjibRf0cHrjX26NqqeH6jvqrnNbOYaxRe/zbQWXs3Lx1jZg8Rh7a3i5SCXY3UGKm0uVfeASPM7HAaRgwZaml2tXsJW4Gkz0YxOvfAWB+LRNredQSHHUHpfIxZU24oMDYgm2yWpsa2jEbJsdMtv3yoRyv2BHDCyCjmfwfFJpxqfrG1kJdjiGqahsuamv7mf3nPmnRCdVLPlwCPhp/BlcqYGNpkhXi0q4/RYU2BB4W+8ZOHfjkXN7ff8KHjz/Jux5U4LRHN0PBxfqnrLByZHFCXp7fT1SM8QUFTovHX7BsSdUWL2ufs+CMeG4H6pPk///VKx0AqVmY4T7pk0xnqbvTZvPQck0jXitDSjRQCo2J8v6tBzQfrWW5nnpqSGKsJyxXQMkjRMMn7VQ68H6VCJjgjKRV1duN7RMw2h8K04FZR0a0emyVyQZFw6HcnSlHQPSuy5/c04jpLZymKWlYVJXkXzrKO6W2ry0TTdRDJmQzxbeeYbmSKlnlZZWXnmeozVDy8mHv99134P93KzGDoet8CCo+WSiz7aYbcIvPwA72bSCnM+XOylHOD45kEV0a99xaLhHV6GjexY4yVPn0z4mRk5/f4WorR2te3rYJRobb29qRBR1TlMZb8LvHPz5cRSzHP2k5WdviEmuvTYhwx60CsOlxKKBo0cXi93ig3MJg=
  file:
    - "package.json"
  overwrite: true
  skip_cleanup: true
  draft: true
  name: "TEST RELEASE DRAFT"
  tag_name: "release_draft"
  on:
    repo: ORNL-AMO/AMO-Tools-Desktop
    branch: issue-3505
    tags: false
